Bug fixed.
dlam28/ulacitbnb pull request #19
Opened 2021-07-18 20:46 UTC by fabrisiocm

Fixed two lines for the ExecuteNonQuery function.

2021-07-18 21:41 UTC, dlam28 commented on ulacitbnb/Controllers/PaymentController.cs
> +                    int rowsAfected = sqlCommand.ExecuteNonQuery();
Change rowsAfected to "rowsAffected".

2021-07-18 21:41 UTC, dlam28 commented on ulacitbnb/Controllers/PaymentController.cs
> +                    int rowsAfected = sqlCommand.ExecuteNonQuery();
Change rowsAfected to "rowsAffected".

2021-07-18 21:41 UTC, dlam28 commented on ulacitbnb/Controllers/ReservationController.cs
> +                    int rowsAfected = sqlCommand.ExecuteNonQuery();
Change rowsAfected to "rowsAffected".

2021-07-18 23:02 UTC, Gabuardi requested changes

2021-07-18 23:02 UTC, Gabuardi commented on ulacitbnb/Controllers/PaymentController.cs
> +                    int rowsAffected = sqlCommand.ExecuteNonQuery();
There is no need to create a variable, just do this

```suggestion
                    sqlCommand.ExecuteNonQuery();
```

2021-07-21 21:27 UTC, Gabuardi approved these changes

2021-07-21 21:27 UTC, merged