Dlam controller service
dlam28/ulacitbnb pull request #2
Opened 2021-06-29 18:32 UTC by DLam28

Implementation of Controller Service.

2021-06-29 19:26 UTC, Gabuardi requested changes

2021-06-29 19:26 UTC, Gabuardi commented on Controllers/ServiceController.cs
> +                using (SqlConnection sqlConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["ULACITBnB"].ConnectionString))
This line could be separated into the following:
```c#
SqlConnection sqlConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["ULACITBnB"].ConnectionString)
using (sqlConnection)
```
Moving the declaration of the variable outside the `using` the code looks more readable, are you agree?

2021-06-29 19:26 UTC, Gabuardi commented on Controllers/ServiceController.cs
> +        //GET GetId
Are this comments really necessary? we already have the HTTPAction above.
If the purpose is to make clear the division between the methods maybe we could use something like this:
```c#
// ---------------------------------------------------
```

2021-06-29 19:26 UTC, Gabuardi commented on Controllers/ServiceController.cs
> +
Empty line unnecessary

2021-06-29 19:26 UTC, Gabuardi commented on Controllers/ServiceController.cs
> +                return BadRequest("Please enter required fields to create a service.");
I like this! nice touch

2021-06-29 19:26 UTC, Gabuardi commented on Controllers/ServiceController.cs
> +            return Ok(service);
I think is more useful send the afectedRows rather than the service

2021-06-29 19:26 UTC, Gabuardi commented on Controllers/ServiceController.cs
> +                    int filasAfectadas = sqlCommand.ExecuteNonQuery();
english language convention please

2021-06-29 21:18 UTC, Gabuardi approved these changes
good job! LGTM!

2021-06-30 00:58 UTC, lguzmanc433 approved these changes

2021-06-30 00:59 UTC, merged